/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package parcial2.Components;

/**
 *
 * @author nahuelpaez
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appNameLabel = new javax.swing.JLabel();
        userSelect = new javax.swing.JLabel();
        booksSelect = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(149, 204, 137));

        appNameLabel.setFont(new java.awt.Font("Phosphate", 2, 18)); // NOI18N
        appNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        appNameLabel.setText("BookApp");

        userSelect.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        userSelect.setForeground(new java.awt.Color(255, 255, 255));
        userSelect.setText("Usuarios");
        userSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userSelectMouseClicked(evt);
            }
        });

        booksSelect.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        booksSelect.setForeground(new java.awt.Color(255, 255, 255));
        booksSelect.setText("Libros");
        booksSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksSelectMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(userSelect)
                    .addComponent(appNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(booksSelect, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(appNameLabel)
                .addGap(45, 45, 45)
                .addComponent(userSelect)
                .addGap(18, 18, 18)
                .addComponent(booksSelect)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(298, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userSelectMouseClicked
       
    }//GEN-LAST:event_userSelectMouseClicked

    private void booksSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksSelectMouseClicked
        
    }//GEN-LAST:event_booksSelectMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JLabel booksSelect;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel userSelect;
    // End of variables declaration//GEN-END:variables
}
